# -*- coding: utf-8 -*-
"""Heart Disease

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgmIZXIKlsqneEweDBfx0OEmMguf9mfs
"""

# 1. Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score

# 2. Crear dataset simulado (ejemplo)
data = {
    "age": [63, 37, 41, 56, 57, 57, 56, 44, 52, 57, 60, 45, 50, 65, 48, 62, 38, 55, 47, 61],
    "sex": [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    "cp": [1, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 1, 2, 1, 2, 0, 1, 1, 0, 2],
    "trestbps": [145, 130, 130, 120, 120, 140, 140, 120, 172, 150, 132, 128, 140, 138, 110, 150, 120, 135, 125, 145],
    "chol": [233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 210, 240, 230, 289, 220, 260, 215, 280, 222, 275],
    "thalach": [150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 180, 175, 160, 155, 170, 150, 185, 165, 177, 159],
    "target": [1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)


# 3. Variables predictoras (X) y variable objetivo (y)
X = df[["age", "trestbps", "chol"]]   # Ejemplo: edad, presión en reposo y colesterol
y = df["thalach"]                     # Variable continua: frecuencia cardiaca máxima

# 4. División en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Modelo de Regresión Lineal
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

# 6. Predicciones
y_pred = lin_model.predict(X_test)

# 7. Evaluación
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Evaluación Regresión Lineal:")
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

# 8. Gráfico de valores reales vs predichos
plt.scatter(y_test, y_pred, alpha=0.6)
plt.xlabel("Valores reales (thalach)")
plt.ylabel("Predicciones")
plt.title("Regresión Lineal - Predicción de Frecuencia Cardíaca Máxima")
plt.show()